### PR TITLE
Split ConfigurationLoader into ConfigStore and ConfigRegistry

### PR DESCRIPTION
**Pull request by chriszarate**
A hopefully uncontroversial naming change that paces the way for global access functions. `ConfigurationLoader` was a poor name (guilty!) and was doing two very different jobs. This splits the class and updates all references. No functional changes.

A follow-on PR will introduce access functions and update docs.

### CODE REVIEW

**Comment by maxschmeling** [comment]
If I'm understanding the purpose correctly on quick glance, isn't it more of a `ConfigRegistrar` than `ConfigRegistry`?

Not sure I like the `Registrar` name either though. But `Registry` and `Store` seem like synonyms.

**Comment by chriszarate** [comment]
Happy to change it, the main thing is having the store / access separate from the entrypoints to register things.

**Comment by chriszarate** [comment]
@maxschmeling FWIW I was following WP patterns for this, which has lots of `Registry` classes with `register_*` methods:

https://github.com/search?q=repo:WordPress/wordpress-develop%20registry&type=code

**Comment by maxschmeling** [comment]
Might be a slight difference from some of those in the link because in those cases, they actually are registering with internal state. But having the name match up makes sense. And it's probably a pedantic argument and probably doesn't matter.

LGTM 🚢

**Review by mhsdef — APPROVED** [review]
@maxschmeling not pedantic, this stuff matters a ton over time. I have seen so much complexity build in large codebases _just_ from people confused over wtf this abstraction meant vs that abstraction (and giving up a rolling their own third thing).

This feels like a step in the right direction as long as we aren't overly attached to exactly what it is here. Eg, I think, ultimately, we may need to break down query vs block registration concerns.

:shipit:

**Comment by chriszarate** [comment]
> Eg, I think, ultimately, we may need to break down query vs block registration concerns.

Indeed

**Pull request merged**
